config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #get 'page/home', to:'page#home'
  root to:'page#home'

  get 'page/about', to:'page#about'

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base

validates :title, presence: true, length:{minimun:4, maximum:40}
validates :description, presence: true, length:{minimun:20, maximum:500}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def new
	@article = Article.new

end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

def home

end

def about

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/articles/new.html.erb
<h1>Create an article !!</h1>

<%= form_for @article do |f| %>

<p>
	<%= f.label :title %></p>
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :description %></p>
	<%= f.text_area :description %>
</p>
<p><%= f.submit %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railscrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/about.html.erb
<h1>This is about page</h1>

<%= link_to "Home", root_path %>

app/views/page/home.html.erb
<h1>This is home page</h1>

<%= link_to "About", page_about_path %>